# Generated by Django 3.0.4 on 2021-05-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_auto_20200905_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosms',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infosms',
            name='from_number',
            field=models.CharField(max_length=11, verbose_name='발신번호'),
        ),
    ]
