# Generated by Django 3.0.4 on 2021-05-04 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_auto_20210504_1432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoSms',
        ),
    ]
