steps:
- name: python:3.7
  entrypoint: python3
  args: ['-m', 'pip', 'install', '-r', 'myplatform/requirements.txt', '--user']
- name: 'python:3.7'                                            
  entrypoint: python3                                                           
  args: ['myplatform/manage.py', 'collectstatic', '--noinput']