# Generated by Django 3.0.4 on 2020-11-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagyeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='성명')),
                ('companyprofile_id', models.IntegerField(null=True)),
                ('birth', models.CharField(blank=True, max_length=8, null=True, verbose_name='생년월일')),
                ('term_from_to', models.CharField(blank=True, max_length=18, null=True, verbose_name='계약기간')),
                ('zipcode', models.CharField(blank=True, max_length=7, null=True, verbose_name='우편번호')),
                ('addr', models.CharField(blank=True, max_length=150, null=True, verbose_name='주소')),
                ('addr_2', models.CharField(blank=True, max_length=150, null=True, verbose_name='상세주소')),
                ('ip_start', models.DateField(blank=True, null=True, verbose_name='입사일')),
                ('ip_end', models.DateField(blank=True, null=True, verbose_name='퇴사일')),
                ('mng_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='관리자ID')),
                ('telno', models.CharField(blank=True, max_length=20, null=True, verbose_name='연락처')),
            ],
            options={
                'verbose_name_plural': '파견사원 / Pagyeon',
                'db_table': 'pagyeon_pagyeon',
                'managed': False,
            },
        ),
    ]
