# Generated by Django 3.0.4 on 2021-02-01 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hr_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('custname', models.CharField(blank=True, max_length=100, null=True, verbose_name='회사명')),
                ('custid', models.CharField(blank=True, max_length=13, null=True, verbose_name='사업자번호')),
                ('emp_count', models.IntegerField(blank=True, null=True, verbose_name='임직원수')),
                ('gross_total', models.IntegerField(blank=True, null=True, verbose_name='매출액')),
                ('homepage', models.URLField(blank=True, null=True, verbose_name='홈페이지')),
                ('introduce', models.TextField(blank=True, max_length=10000, null=True, verbose_name='회사소개')),
                ('manager_email', models.CharField(blank=True, max_length=30, null=True, verbose_name='HR이메일')),
                ('manager_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='HR연락처')),
                ('company_logo', models.FileField(blank=True, null=True, upload_to=hr_profile.models.hr_directory_path, verbose_name='HR회사 로고')),
                ('attachments', models.FileField(blank=True, null=True, upload_to=hr_profile.models.hr_directory_path, verbose_name='첨부파일')),
                ('load_addr_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='주소(도로명코드)')),
                ('load_addr', models.CharField(blank=True, max_length=50, null=True, verbose_name='주소(도로명주소)')),
                ('load_addr_detail', models.CharField(blank=True, max_length=50, null=True, verbose_name='주소 상세')),
                ('address', models.ForeignKey(blank=True, limit_choices_to={'comidx': 'BE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.ComCode', verbose_name='회사위치')),
                ('cmp_manager', models.ForeignKey(blank=True, limit_choices_to={'is_admin': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hr_cmp_manager', to=settings.AUTH_USER_MODEL, verbose_name='담당매니저')),
                ('status_cd', models.ForeignKey(blank=True, default='CB0100000', limit_choices_to={'comidx': 'CB'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_status_cd', to='backend.ComCode', verbose_name='승인상태')),
                ('user', models.ManyToManyField(related_name='hrprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'HR 프로필 / HRProfile',
            },
        ),
        migrations.CreateModel(
            name='HrSpecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('jikjong_tax_start', models.IntegerField(null=True, verbose_name='직종(중) 수수료 시작')),
                ('jikjong_tax_end', models.IntegerField(null=True, verbose_name='직종(중) 수수료 종료')),
                ('hr_jikjong_low', models.ManyToManyField(blank=True, related_name='hrspecial_jikjong_low', to='backend.ComCode', verbose_name='직종코드(소)')),
                ('hr_jikjong_mid', models.ForeignKey(blank=True, limit_choices_to={'comidx': 'AA'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hrspecial_jikjong_mid', to='backend.ComCode', verbose_name='직종코드(중)')),
                ('hr_jikjong_top', models.ForeignKey(blank=True, limit_choices_to={'code_topcd': None, 'comidx': 'AA'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hrspecial_jikjong_top', to='backend.ComCode', verbose_name='직종코드(대)')),
                ('hrprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hrspecial', to='hr_profile.HrProfile')),
            ],
            options={
                'verbose_name_plural': '전문직종 / HrSpecial',
            },
        ),
        migrations.CreateModel(
            name='HrProfileCoWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('coworker_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='연락처')),
                ('hrprofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_coworker', to='hr_profile.HrProfile', verbose_name='회사프로필')),
                ('hrprofile_auth', models.ForeignKey(blank=True, default='CG0200000', limit_choices_to={'comidx': 'CG'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.ComCode', verbose_name='기업권한')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrprofilecoworker', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'HR회사동료 / HrProfileCoWorker',
            },
        ),
    ]
