# Generated by Django 3.0.4 on 2021-02-03 10:12

from django.db import migrations, models
import django.db.models.deletion
import hr_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('hr_image', models.ImageField(blank=True, null=True, upload_to=hr_profile.models.hr_directory_path, verbose_name='HR 회사 이미지')),
                ('hrprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hrprofile_image', to='hr_profile.HrProfile')),
            ],
            options={
                'verbose_name_plural': 'HR 이미지 / HrImage',
            },
        ),
        migrations.CreateModel(
            name='HrFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('hr_file', models.FileField(blank=True, null=True, upload_to=hr_profile.models.hr_directory_path, verbose_name='첨부파일')),
                ('hrprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hrprofile_file', to='hr_profile.HrProfile')),
            ],
            options={
                'verbose_name_plural': 'HR 파일 / HrFile',
            },
        ),
    ]
