# Generated by Django 3.0.4 on 2021-02-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_profile', '0002_hrfile_hrimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrprofile',
            name='attachments',
        ),
    ]
