# Generated by Django 3.0.4 on 2021-02-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_profile', '0004_auto_20210205_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrspecial',
            name='jikjong_tax_end',
            field=models.FloatField(null=True, verbose_name='직종(중) 수수료 종료'),
        ),
        migrations.AlterField(
            model_name='hrspecial',
            name='jikjong_tax_start',
            field=models.FloatField(null=True, verbose_name='직종(중) 수수료 시작'),
        ),
    ]
