# Generated by Django 3.0.4 on 2021-02-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_profile', '0005_auto_20210216_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrprofile',
            name='homepage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='홈페이지'),
        ),
    ]
