# Generated by Django 3.0.4 on 2021-02-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_profile', '0006_auto_20210225_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrprofile',
            name='homepage',
            field=models.URLField(blank=True, null=True, verbose_name='홈페이지'),
        ),
    ]
