# Generated by Django 3.0.4 on 2021-03-30 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_profile', '0008_auto_20210225_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hrprofile',
            options={'verbose_name_plural': '1. HR 프로필 / HRProfile'},
        ),
        migrations.AlterModelOptions(
            name='hrprofilecoworker',
            options={'verbose_name_plural': '1_1. HR회사동료 / HrProfileCoWorker'},
        ),
    ]
