# Generated by Django 3.0.4 on 2021-04-23 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_profile', '0009_auto_20210330_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrAccountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('account_name', models.CharField(max_length=50, verbose_name='청구담당자명')),
                ('account_phone', models.CharField(max_length=13, verbose_name='청구담당자연락처')),
                ('account_email', models.EmailField(max_length=254, verbose_name='계산서발행 Email')),
                ('hrprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hraccount', to='hr_profile.HrProfile', verbose_name='청구')),
            ],
            options={
                'verbose_name_plural': '청구정보 / HrAccountInfo',
            },
        ),
    ]
