# Generated by Django 3.0.4 on 2021-04-28 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_profile', '0010_hraccountinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hraccountinfo',
            options={'verbose_name_plural': '3. 청구정보 / HrAccountInfo'},
        ),
        migrations.AlterModelOptions(
            name='hrspecial',
            options={'verbose_name_plural': '2. 전문직종 / HrSpecial'},
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='is_expose',
            field=models.BooleanField(default=False, verbose_name='노출여부'),
        ),
        migrations.AlterField(
            model_name='hraccountinfo',
            name='hrprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hraccountinfo', to='hr_profile.HrProfile', verbose_name='청구'),
        ),
    ]
