# Generated by Django 3.0.4 on 2021-04-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20210423_1032'),
        ('hr_profile', '0011_auto_20210428_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='faxno',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='팩스번호'),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='service_address',
            field=models.ManyToManyField(blank=True, limit_choices_to={'comidx': 'BE'}, null=True, to='backend.ComCode', verbose_name='서비스지역'),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='since',
            field=models.IntegerField(blank=True, null=True, verbose_name='설립년도'),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='telno',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='대표번호'),
        ),
    ]
