# Generated by Django 3.0.4 on 2021-05-07 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_profile', '0012_auto_20210428_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrprofilecoworker',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hrprofilecoworker', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
