# Generated by Django 3.0.4 on 2021-05-26 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20210507_1406'),
        ('hr_profile', '0013_auto_20210507_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrprofile',
            name='service_address',
            field=models.ManyToManyField(blank=True, limit_choices_to={'comidx': 'BE'}, null=True, related_name='service_address', to='backend.ComCode', verbose_name='서비스지역'),
        ),
        migrations.CreateModel(
            name='HrFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('start', models.IntegerField(verbose_name='구간시작')),
                ('end', models.IntegerField(verbose_name='구간종료')),
                ('fee', models.FloatField(verbose_name='수수료율(%)')),
                ('fee_gubun', models.ForeignKey(blank=True, limit_choices_to={'comidx': 'CH'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ComCode', verbose_name='수수료 구분')),
                ('hrprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_profile.HrProfile', verbose_name='HR회사')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
