# Generated by Django 3.0.4 on 2021-05-27 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20210507_1406'),
        ('hr_profile', '0014_auto_20210526_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrfee',
            name='fee',
        ),
        migrations.AddField(
            model_name='hrfee',
            name='fee_end',
            field=models.FloatField(default=0, verbose_name='수수료율 종료(%)'),
        ),
        migrations.AddField(
            model_name='hrfee',
            name='fee_start',
            field=models.FloatField(default=0, verbose_name='수수료율 시작(%)'),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='services',
            field=models.ManyToManyField(blank=True, limit_choices_to={'comidx': 'AC'}, null=True, related_name='services', to='backend.ComCode', verbose_name='제공서비스'),
        ),
        migrations.AlterField(
            model_name='hrfee',
            name='end',
            field=models.IntegerField(default=0, verbose_name='구간종료'),
        ),
        migrations.AlterField(
            model_name='hrfee',
            name='fee_gubun',
            field=models.ForeignKey(blank=True, limit_choices_to={'comidx': 'AC'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ComCode', verbose_name='수수료 구분'),
        ),
        migrations.AlterField(
            model_name='hrfee',
            name='start',
            field=models.IntegerField(default=0, verbose_name='구간시작'),
        ),
    ]
