# Generated by Django 3.0.4 on 2021-06-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_profile', '0016_auto_20210607_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrprofile',
            name='status_reason',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='상태사유(거절사유)'),
        ),
    ]
