# Generated by Django 3.0.4 on 2021-03-16 14:46

from django.db import migrations, models
import django.db.models.deletion
import employee.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_profile', '0008_auto_20210225_1623'),
        ('company_profile', '0015_auto_20210225_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('contract_from', models.DateField(blank=True, null=True, verbose_name='계약시작일')),
                ('contract_to', models.DateField(blank=True, null=True, verbose_name='계약종료일')),
                ('direct_cost', models.IntegerField(blank=True, default=0, null=True, verbose_name='직접비(Month)')),
                ('contract_gigan', models.IntegerField(blank=True, default=0, null=True, verbose_name='계약기간')),
                ('fee', models.IntegerField(blank=True, default=0, null=True, verbose_name='수수료')),
            ],
            options={
                'verbose_name_plural': '계약 / Contract',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('emp_name', models.CharField(max_length=100, verbose_name='사원명')),
                ('emp_phone', models.CharField(max_length=100, verbose_name='연락처')),
                ('emp_birth', models.CharField(max_length=10, verbose_name='생년월일')),
            ],
            options={
                'verbose_name_plural': '사원 / Employee',
            },
        ),
        migrations.CreateModel(
            name='ContractFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to=employee.models.contract_directory_path, verbose_name='HR 회사 이미지')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_file', to='employee.Contract')),
            ],
            options={
                'verbose_name_plural': '계약첨부파일 / ContractAttach',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_employee', to='employee.Employee'),
        ),
        migrations.AddField(
            model_name='contract',
            name='hrprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_hrprofile', to='hr_profile.HrProfile', verbose_name='파견사업주'),
        ),
        migrations.AddField(
            model_name='contract',
            name='sugub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_sugub', to='company_profile.Sugub', verbose_name='수급'),
        ),
    ]
