# Generated by Django 3.0.4 on 2021-03-19 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210317_0941'),
        ('employee', '0003_auto_20210319_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='chae_cd',
            field=models.ForeignKey(blank=True, limit_choices_to={'code_topcd': None, 'comidx': 'AC'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ComCode', verbose_name='채용형태'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_from',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='계약시작일'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_to',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='계약종료일'),
            preserve_default=False,
        ),
    ]
