# Generated by Django 3.0.4 on 2021-03-19 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210319_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_from',
            field=models.DateField(blank=True, null=True, verbose_name='계약시작일'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_to',
            field=models.DateField(blank=True, null=True, verbose_name='계약종료일'),
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('fee', models.IntegerField(default=0, verbose_name='수수료')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_contract', to='employee.Contract')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
