# Generated by Django 3.0.4 on 2021-03-19 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20210319_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee',
            options={'verbose_name_plural': '3. 수수료 / Fee'},
        ),
        migrations.AlterField(
            model_name='fee',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_contract', to='employee.Contract'),
        ),
    ]
