# Generated by Django 3.0.4 on 2021-03-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20210319_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='fee',
        ),
    ]
