# Generated by Django 3.0.4 on 2021-03-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_remove_contract_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_confirm',
            field=models.BooleanField(default=False, verbose_name='관리자확인'),
        ),
    ]
