# Generated by Django 3.0.4 on 2021-03-30 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210330_1113'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_profile', '0009_auto_20210330_1113'),
        ('employee', '0008_contract_is_confirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True, max_length=2000, null=True, verbose_name='요청사유')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_employee', to='employee.Employee', verbose_name='환불 대상자')),
                ('gubun', models.ForeignKey(default='ZF0100000', limit_choices_to={'comidx': 'ZF'}, on_delete=django.db.models.deletion.CASCADE, related_name='refund_gubun', to='backend.ComCode', verbose_name='환불방식')),
                ('hrprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_hrprofile', to='hr_profile.HrProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_user', to=settings.AUTH_USER_MODEL, verbose_name='요청자')),
            ],
            options={
                'verbose_name_plural': '4. 환불 / Refund',
            },
        ),
        migrations.CreateModel(
            name='RefundFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('refund_file', models.FileField(blank=True, null=True, upload_to=employee.models.contract_directory_path, verbose_name='환불관련파일')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Refund')),
            ],
            options={
                'verbose_name_plural': '4_1. 환불첨부파일 / RefundFile',
            },
        ),
    ]
