# Generated by Django 3.0.4 on 2021-03-30 11:50

from django.db import migrations, models
import django.db.models.deletion
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_profile', '0009_auto_20210330_1113'),
        ('employee', '0009_refund_refundfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund_contract', to='employee.Contract', verbose_name='환불 계약'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='hrprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_hrprofile', to='hr_profile.HrProfile', verbose_name='요청회사'),
        ),
        migrations.AlterField(
            model_name='refundfile',
            name='refund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_file', to='employee.Refund'),
        ),
        migrations.AlterField(
            model_name='refundfile',
            name='refund_file',
            field=models.FileField(blank=True, null=True, upload_to=employee.models.refund_directory_path, verbose_name='환불관련파일'),
        ),
    ]
