# Generated by Django 3.0.4 on 2021-03-30 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_auto_20210330_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='employee',
        ),
        migrations.AlterField(
            model_name='refund',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_contract', to='employee.Contract', verbose_name='환불 계약'),
        ),
    ]
