# Generated by Django 3.0.4 on 2021-04-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20210330_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_from',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='계약시작일'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_to',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='계약종료일'),
        ),
    ]
