# Generated by Django 3.0.4 on 2021-04-06 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_auto_20210402_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_contract', to='employee.Contract', verbose_name='환불 계약'),
        ),
    ]
