# Generated by Django 3.0.4 on 2021-04-07 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210406_1348'),
        ('employee', '0013_auto_20210406_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='refund_status',
            field=models.ForeignKey(default='ZG0100000', limit_choices_to={'comidx': 'ZG'}, on_delete=django.db.models.deletion.CASCADE, to='backend.ComCode', verbose_name='환불상태'),
        ),
    ]
