# Generated by Django 3.0.4 on 2021-02-01 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0001_initial'),
        ('company_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='sugub_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sugubreview_point', to='company_profile.SugubReview', verbose_name='수급리뷰'),
        ),
        migrations.AddField(
            model_name='notification',
            name='noti_category',
            field=models.ForeignKey(blank=True, limit_choices_to={'code_topcd': None, 'comidx': 'ZA'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_category', to='backend.ComCode', verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='notification',
            name='noti_level',
            field=models.ForeignKey(blank=True, limit_choices_to={'code_topcd': None, 'comidx': 'ZB'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_level', to='backend.ComCode', verbose_name='알림 레벨'),
        ),
        migrations.AddField(
            model_name='jikjonglow',
            name='compacode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ComPaCode', verbose_name='법정파견코드'),
        ),
        migrations.AddField(
            model_name='jikjonglow',
            name='jikjong_low',
            field=models.OneToOneField(limit_choices_to=models.Q(('comidx', 'AA'), models.Q(_negated=True, code_topcd__endswith='00000'), models.Q(_negated=True, code_topcd=None)), on_delete=django.db.models.deletion.CASCADE, to='backend.ComCode', verbose_name='직종(소)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='faq_gubun',
            field=models.ForeignKey(limit_choices_to={'code_topcd': None, 'comidx': 'ZC'}, on_delete=django.db.models.deletion.CASCADE, to='backend.ComCode', verbose_name='구분값'),
        ),
        migrations.AddField(
            model_name='comcode',
            name='comidx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ComIdx'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_type',
            field=models.ForeignKey(limit_choices_to={'code_topcd': None, 'comidx': 'CE'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_type', to='backend.ComCode', verbose_name='답변유형'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(limit_choices_to=models.Q(_negated=True, question_comment=None), on_delete=django.db.models.deletion.CASCADE, to='backend.Question', verbose_name='질문'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'answer_type', 'answer_comment')},
        ),
    ]
