# Generated by Django 3.0.4 on 2021-02-19 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210201_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('contents', models.TextField(blank=True, max_length=3000, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('link_url', models.URLField(blank=True, null=True)),
                ('alarm_gubun', models.ForeignKey(blank=True, limit_choices_to={'code_topcd': None, 'comidx': 'ZE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.ComCode')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm', to=settings.AUTH_USER_MODEL, verbose_name='받는사람')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
