# Generated by Django 3.0.4 on 2021-02-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alarm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarm',
            options={'ordering': ('-created_time',), 'verbose_name_plural': '알림 / Alarm'},
        ),
    ]
