# Generated by Django 3.0.4 on 2021-03-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210224_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='qna_attach',
            field=models.FileField(null=True, upload_to='media/uploads//qna/', verbose_name='첨부파일'),
        ),
    ]
