# Generated by Django 3.0.4 on 2021-03-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210317_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '1. 사용자 / User'},
        ),
    ]
