# Generated by Django 3.0.4 on 2021-03-30 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210324_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comcode',
            options={'verbose_name_plural': '1_1. 상세코드 / ComCode'},
        ),
        migrations.AlterModelOptions(
            name='comidx',
            options={'verbose_name_plural': '1. 공통코드 INDEX / ComIdx'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '2. 사용자 / User'},
        ),
    ]
