# Generated by Django 3.0.4 on 2021-04-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210406_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='프로필이미지'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='관리자'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_temp',
            field=models.BooleanField(default=False, verbose_name='임시회원'),
        ),
    ]
