# Generated by Django 3.0.4 on 2021-04-12 15:26

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20210407_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(max_length=255, null=True, upload_to=backend.models.user_directory_path, verbose_name='프로필이미지'),
        ),
    ]
