# Generated by Django 3.0.4 on 2021-06-08 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20210507_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_email', models.BooleanField(default=True)),
                ('allow_fcm', models.BooleanField(default=True)),
                ('allow_kakao', models.BooleanField(default=True)),
                ('allow_sms', models.BooleanField(default=True)),
                ('alarm_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ComCode', verbose_name='알림유형')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name_plural': '2_1. 알람설정 / AlarmSetting',
            },
        ),
    ]
