# Generated by Django 3.0.4 on 2021-06-15 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alarmsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmsetting',
            name='alarm_code',
            field=models.ForeignKey(blank=True, limit_choices_to={'code_topcd': None, 'comidx': 'ZH'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ComCode', verbose_name='알림유형'),
        ),
        migrations.AlterField(
            model_name='alarmsetting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_settings', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
