# Generated by Django 3.0.4 on 2021-03-11 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_auto_20210310_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_end',
            field=models.BooleanField(default=False, verbose_name='종료상태'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='chatroom', to=settings.AUTH_USER_MODEL, verbose_name='참여자'),
        ),
    ]
