# Generated by Django 3.0.4 on 2021-03-18 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_auto_20210311_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='exit_participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='chatroom_exit_participants', to=settings.AUTH_USER_MODEL, verbose_name='퇴장'),
        ),
    ]
