# Generated by Django 3.0.4 on 2021-02-01 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0002_auto_20210201_1656'),
        ('company_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicant',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.Resume', verbose_name='이력서'),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='url_recuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_recuser', to=settings.AUTH_USER_MODEL, verbose_name='URL추천인'),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='jobanswer',
            name='job_answer_type',
            field=models.ForeignKey(limit_choices_to={'code_topcd': None, 'comidx': 'CE'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_answer_type', to='backend.ComCode', verbose_name='답변유형'),
        ),
        migrations.AddField(
            model_name='jobanswer',
            name='jobquestion',
            field=models.ForeignKey(limit_choices_to=models.Q(_negated=True, job_question_comment=None), on_delete=django.db.models.deletion.CASCADE, related_name='jobanswers', to='company_profile.JobQuestion', verbose_name='질문'),
        ),
        migrations.AddField(
            model_name='jobadvertise',
            name='job_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_admin': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='담당매니저'),
        ),
        migrations.AddField(
            model_name='jobadvertise',
            name='job_reward_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'code_topcd': None, 'comidx': 'GA'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_reward_type', to='backend.ComCode', verbose_name='보상금종류'),
        ),
        migrations.AddField(
            model_name='jobadvertise',
            name='job_reward_way',
            field=models.ForeignKey(blank=True, limit_choices_to={'code_topcd': None, 'comidx': 'GB'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_reward_way', to='backend.ComCode', verbose_name='보상지급방식'),
        ),
        migrations.AddField(
            model_name='jobadvertise',
            name='jobadvertise_status',
            field=models.ForeignKey(blank=True, default='CA0100000', limit_choices_to={'code_topcd': None, 'comidx': 'CA'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobadvertise_status', to='backend.ComCode', verbose_name='공개상태코드'),
        ),
        migrations.AddField(
            model_name='jobadvertise',
            name='sugub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobadvertise', to='company_profile.Sugub'),
        ),
        migrations.AddField(
            model_name='importpaymenthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymenthistory', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='companyprofilecoworker',
            name='companyprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_coworker', to='company_profile.CompanyProfile', verbose_name='회사프로필'),
        ),
        migrations.AddField(
            model_name='companyprofilecoworker',
            name='companyprofile_auth',
            field=models.ForeignKey(blank=True, default='CG0200000', limit_choices_to={'comidx': 'CG'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.ComCode', verbose_name='기업권한'),
        ),
        migrations.AddField(
            model_name='companyprofilecoworker',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyprofilecoworker', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='cmp_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_admin': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cmp_manager', to=settings.AUTH_USER_MODEL, verbose_name='담당매니저'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_form',
            field=models.ForeignKey(blank=True, default='CF0100000', limit_choices_to={'comidx': 'CF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_form', to='backend.ComCode', verbose_name='기업형태'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_recuser',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companyrecuser', to=settings.AUTH_USER_MODEL, verbose_name='추천인'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='status_cd',
            field=models.ForeignKey(blank=True, default='CB0100000', limit_choices_to={'comidx': 'CB'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ComCode', verbose_name='승인상태'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='user',
            field=models.ManyToManyField(related_name='companyprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='sugubreview',
            unique_together={('sugub', 'user', 'hrprofile')},
        ),
        migrations.AlterUniqueTogether(
            name='jobapplicant',
            unique_together={('jobadvertise', 'user')},
        ),
    ]
