# Generated by Django 3.0.4 on 2021-02-01 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210201_1656'),
        ('hr_profile', '0001_initial'),
        ('company_profile', '0004_jobapplicant_hrprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicant',
            name='hrprofile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_profile.HrProfile', verbose_name='HR회사'),
        ),
        migrations.AlterField(
            model_name='sugub',
            name='sugub_gender',
            field=models.ForeignKey(blank=True, limit_choices_to={'code_topcd': None, 'comidx': 'AQ'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sugub_gender', to='backend.ComCode', verbose_name='선호성별'),
        ),
    ]
