# Generated by Django 3.0.4 on 2021-02-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0006_auto_20210205_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='introduce',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='간단소개글'),
        ),
    ]
