# Generated by Django 3.0.4 on 2021-02-16 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company_profile', '0008_sugubreview_companyprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sugub',
            name='chae_cd_name',
        ),
        migrations.AlterField(
            model_name='sugubreview',
            name='companyprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_profile.CompanyProfile', verbose_name='사용사업주'),
        ),
        migrations.AlterField(
            model_name='sugubreview',
            name='sugub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sugub_reviews', to='company_profile.Sugub', verbose_name='수급'),
        ),
        migrations.AlterUniqueTogether(
            name='sugubreview',
            unique_together={('sugub', 'user')},
        ),
        migrations.RemoveField(
            model_name='sugubreview',
            name='review_point',
        ),
    ]
