# Generated by Django 3.0.4 on 2021-02-17 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_profile', '0005_auto_20210216_1017'),
        ('company_profile', '0009_auto_20210216_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugubreview',
            name='hrprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_sugub_reviews', to='hr_profile.HrProfile', verbose_name='HR회사'),
        ),
    ]
