# Generated by Django 3.0.4 on 2021-02-17 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210201_1656'),
        ('company_profile', '0010_auto_20210217_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugub',
            name='salary_gubun',
            field=models.ForeignKey(blank=True, limit_choices_to={'code_use': True, 'comidx': 'AI'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_gubun', to='backend.ComCode', verbose_name='급여형태(AI)'),
        ),
    ]
