# Generated by Django 3.0.4 on 2021-02-24 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0004_auto_20210224_1407'),
        ('company_profile', '0011_auto_20210217_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sugub',
            name='cont_month',
        ),
        migrations.RemoveField(
            model_name='sugub',
            name='cont_term_gubun',
        ),
        migrations.AlterField(
            model_name='jobadvertise',
            name='jobadvertise_status',
            field=models.ForeignKey(blank=True, default='CA0200000', limit_choices_to={'code_topcd': None, 'comidx': 'CA'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobadvertise_status', to='backend.ComCode', verbose_name='공개상태코드'),
        ),
        migrations.AlterField(
            model_name='jobapplicant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to=settings.AUTH_USER_MODEL, verbose_name='지원자'),
        ),
    ]
