# Generated by Django 3.0.4 on 2021-02-25 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210224_1407'),
        ('company_profile', '0014_auto_20210225_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugub',
            name='work_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'code_topcd': None, 'comidx': 'AG'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_type', to='backend.ComCode', verbose_name='근무형태(AG)'),
        ),
    ]
