# Generated by Django 3.0.4 on 2021-03-17 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0015_auto_20210225_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobadvertise',
            name='job_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads//jobad/', verbose_name='채용공고 이미지(BG)'),
        ),
        migrations.AlterField(
            model_name='jobadvertise',
            name='job_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads//jobad/', verbose_name='채용공고 이미지'),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('interview_dt', models.DateTimeField(verbose_name='면접일정')),
                ('comments', models.TextField(verbose_name='코멘트')),
                ('addr_code', models.IntegerField(max_length=5, verbose_name='면접장소(도로명코드)')),
                ('addr', models.CharField(max_length=100, verbose_name='면접장소')),
                ('addr_detail', models.CharField(max_length=100, verbose_name='면접장소(상세)')),
                ('jobapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_jobapp', to='company_profile.JobApplicant', verbose_name='지원자')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
