# Generated by Django 3.0.4 on 2021-03-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0016_auto_20210317_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='addr_code',
            field=models.CharField(max_length=5, verbose_name='면접장소(도로명코드)'),
        ),
    ]
