# Generated by Django 3.0.4 on 2021-03-24 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0019_estimate_estimatefile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimate',
            options={'verbose_name_plural': '2_1. 예상견적서 / Estimate'},
        ),
        migrations.AlterModelOptions(
            name='sugubreview',
            options={'verbose_name_plural': '2_2. 리뷰 / SugubReview'},
        ),
        migrations.AlterField(
            model_name='estimate',
            name='sugub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_sugub', to='company_profile.Sugub', verbose_name='수급'),
        ),
        migrations.AlterField(
            model_name='estimatefile',
            name='estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_file', to='company_profile.Estimate'),
        ),
    ]
