# Generated by Django 3.0.4 on 2021-03-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0020_auto_20210324_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='comments',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='코멘트'),
        ),
    ]
