# Generated by Django 3.0.4 on 2021-04-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0023_auto_20210423_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interview_email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='인터뷰 담당자 이메일'),
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_manager',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='인터뷰 담당자명'),
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='인터뷰 담당자 연락처'),
        ),
    ]
