# Generated by Django 3.0.4 on 2021-05-14 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20210507_1406'),
        ('company_profile', '0025_auto_20210507_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugub',
            name='ot_daily',
            field=models.IntegerField(default=0, verbose_name='포괄임금(연장)'),
        ),
        migrations.AddField(
            model_name='sugub',
            name='ot_daily_yn',
            field=models.BooleanField(default=False, verbose_name='포괄임금(연장) 유무'),
        ),
        migrations.AddField(
            model_name='sugub',
            name='ot_holiday',
            field=models.IntegerField(default=0, verbose_name='포괄임금(휴일)'),
        ),
        migrations.AddField(
            model_name='sugub',
            name='ot_holiday_yn',
            field=models.BooleanField(default=False, verbose_name='포괄임금(휴일) 유무'),
        ),
        migrations.AddField(
            model_name='sugub',
            name='ot_night',
            field=models.IntegerField(default=0, verbose_name='포괄임금(야간)'),
        ),
        migrations.AddField(
            model_name='sugub',
            name='ot_night_yn',
            field=models.BooleanField(default=False, verbose_name='포괄임금(야간) 유무'),
        ),
        migrations.AlterField(
            model_name='jobadvertise',
            name='company_name_yn',
            field=models.BooleanField(default=False, verbose_name='회사명 비공개'),
        ),
        migrations.AlterField(
            model_name='jobadvertise',
            name='condition_yn',
            field=models.BooleanField(default=False, verbose_name='자격조건 비공개'),
        ),
        migrations.AlterField(
            model_name='jobadvertise',
            name='dpt_name_yn',
            field=models.BooleanField(default=False, verbose_name='부서명 비공개'),
        ),
        migrations.AlterField(
            model_name='jobadvertise',
            name='location_yn',
            field=models.BooleanField(default=False, verbose_name='회사위치 비공개'),
        ),
        migrations.AlterField(
            model_name='jobadvertise',
            name='main_work_yn',
            field=models.BooleanField(default=False, verbose_name='주요업무 비공개'),
        ),
        migrations.AlterField(
            model_name='jobadvertise',
            name='salary_yn',
            field=models.BooleanField(default=False, verbose_name='급여 비공개'),
        ),
        migrations.AlterField(
            model_name='jobadvertise',
            name='special_condition_yn',
            field=models.BooleanField(default=False, verbose_name='우대조건 비공개'),
        ),
        migrations.AlterField(
            model_name='jobadvertise',
            name='welfare_yn',
            field=models.BooleanField(default=False, verbose_name='혜택 및 복지 비공개'),
        ),
        migrations.AlterField(
            model_name='sugub',
            name='sugub_gender',
            field=models.ForeignKey(blank=True, default='AQ0300000', limit_choices_to={'code_topcd': None, 'comidx': 'AQ'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sugub_gender', to='backend.ComCode', verbose_name='선호성별'),
        ),
    ]
