# Generated by Django 3.0.4 on 2021-05-20 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20210507_1406'),
        ('company_profile', '0026_auto_20210514_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugub',
            name='hire_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'code_topcd': None, 'comidx': 'AD'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hire_type', to='backend.ComCode', verbose_name='고용형태(AD)'),
        ),
    ]
