# Generated by Django 3.0.4 on 2021-05-26 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company_profile', '0027_auto_20210520_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicant',
            name='hrmanager',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hrmanager', to=settings.AUTH_USER_MODEL, verbose_name='담당자'),
        ),
    ]
