# Generated by Django 3.0.4 on 2021-06-07 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20210507_1406'),
        ('company_profile', '0029_auto_20210607_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugub',
            name='work_address',
            field=models.ForeignKey(blank=True, limit_choices_to={'code_use': True, 'comidx': 'BE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_address', to='backend.ComCode', verbose_name='지역(BE)'),
        ),
        migrations.AlterField(
            model_name='sugub',
            name='education_cd',
            field=models.ForeignKey(blank=True, limit_choices_to={'code_topcd': None, 'code_use': True, 'comidx': 'AO'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_cd', to='backend.ComCode', verbose_name='학력코드'),
        ),
        migrations.AlterField(
            model_name='sugub',
            name='sugub_career_gb',
            field=models.ForeignKey(blank=True, limit_choices_to={'code_topcd': None, 'code_use': True, 'comidx': 'AB'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sugub_career_gb', to='backend.ComCode', verbose_name='경력코드'),
        ),
    ]
