# Generated by Django 3.0.4 on 2021-06-08 02:57

import company_profile.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company_profile', '0030_auto_20210607_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimate',
            options={'verbose_name_plural': '2_2. 예상견적서 / Estimate'},
        ),
        migrations.AlterModelOptions(
            name='sugubreview',
            options={'verbose_name_plural': '2_3. 리뷰 / SugubReview'},
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_image',
            field=models.ImageField(blank=True, null=True, upload_to=company_profile.models.company_directory_path, verbose_name='회사대표이미지'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to=company_profile.models.company_directory_path, verbose_name='회사로고'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='manager_email',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='대표 이메일'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='대표 연락처'),
        ),
        migrations.CreateModel(
            name='SugubSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('damdang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='damdang_sugubsign', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
                ('sanctioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sanctioner_sugubsign', to=settings.AUTH_USER_MODEL, verbose_name='결재자')),
                ('sugub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sugub_sugubsign', to='company_profile.Sugub', verbose_name='채용의뢰서')),
            ],
            options={
                'verbose_name_plural': '2_1. 수급결재&담당 / SugubSign',
            },
        ),
        migrations.CreateModel(
            name='CompanyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('companyprofile_image', models.ImageField(blank=True, null=True, upload_to=company_profile.models.company_directory_path, verbose_name='회사 이미지')),
                ('companyprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyprofile_image', to='company_profile.CompanyProfile')),
            ],
            options={
                'verbose_name_plural': '회사 이미지 / HrImage',
            },
        ),
    ]
