# Generated by Django 3.0.4 on 2021-02-01 16:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
        ('hr_profile', '0001_initial'),
        ('company_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSpecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('career_gigan', models.IntegerField(blank=True, null=True, verbose_name='경력기간')),
                ('salary_gb', models.CharField(blank=True, max_length=9, null=True, verbose_name='급여코드(AI)')),
                ('currency_gb', models.CharField(blank=True, max_length=9, null=True, verbose_name='통화코드(BQ)')),
                ('salary_amt', models.IntegerField(blank=True, null=True, verbose_name='금액')),
                ('hope_salary', models.IntegerField(blank=True, null=True, verbose_name='희망연봉')),
                ('urlkey', models.CharField(blank=True, max_length=9, null=True)),
                ('open_yn', models.BooleanField(default=True, verbose_name='공개여부')),
                ('answers_json', django_mysql.models.JSONField(default=dict, null=True)),
                ('jikjong_low', models.ManyToManyField(blank=True, limit_choices_to=models.Q(('comidx', 'AA'), models.Q(_negated=True, code_topcd__endswith='00000'), models.Q(_negated=True, code_topcd=None)), related_name='userspecial_jikjong_low', to='backend.ComCode', verbose_name='직종코드(소)')),
                ('jikjong_mid', models.ForeignKey(blank=True, limit_choices_to={'comidx': 'AA'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userspecial_jikjong_mid', to='backend.ComCode', verbose_name='직종코드(중)')),
                ('jikjong_top', models.ForeignKey(blank=True, limit_choices_to={'code_topcd': None, 'comidx': 'AA'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userspecial_jikjong_top', to='backend.ComCode', verbose_name='직종코드(대)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userspecial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '전문분야 / UserSpecial',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=100, null=True, verbose_name='성명')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='연락처')),
                ('date_of_birth', models.CharField(blank=True, max_length=8, null=True, verbose_name='생년월일')),
                ('career_gb', models.CharField(blank=True, max_length=9, null=True, verbose_name='경력구분')),
                ('career_gigan', models.IntegerField(blank=True, null=True, verbose_name='경력기간')),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='최종연봉')),
                ('website', models.URLField(blank=True, null=True, verbose_name='웹사이트')),
                ('about', models.CharField(blank=True, max_length=255, null=True, verbose_name='간단자기소개글')),
                ('gender', models.CharField(blank=True, max_length=1, null=True, verbose_name='성별')),
                ('balance', models.IntegerField(default=0, verbose_name='채공머니')),
                ('address', models.ForeignKey(blank=True, limit_choices_to={'code_topcd': None, 'comidx': 'BE'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='backend.ComCode', verbose_name='사는곳')),
                ('education_level', models.ForeignKey(blank=True, limit_choices_to={'code_topcd': None, 'comidx': 'BX'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_level', to='backend.ComCode', verbose_name='최종학력')),
                ('hope_site', models.ForeignKey(blank=True, limit_choices_to={'code_topcd': None, 'comidx': 'BE'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ComCode', verbose_name='희망근무지')),
                ('recuser', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recuser', to=settings.AUTH_USER_MODEL, verbose_name='추천인')),
                ('status', models.ForeignKey(blank=True, default='BB0200000', limit_choices_to={'code_topcd': None, 'comidx': 'BB'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='backend.ComCode', verbose_name='구직상태')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '사용자 프로필 / UserProfile',
            },
        ),
        migrations.CreateModel(
            name='UserPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('poi_content', models.CharField(blank=True, max_length=50, null=True, verbose_name='포인트 내용')),
                ('poi_point', models.IntegerField(default=0, verbose_name='포인트 점수')),
                ('poi_remain', models.IntegerField(default=0, verbose_name='남은 포인트')),
                ('poi_type', models.ForeignKey(blank=True, limit_choices_to={'code_topcd': None, 'comidx': 'GA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.ComCode', verbose_name='포인트 종류')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userpoint', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': '사용자포인트 / UserPoint',
            },
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('review_comment', models.TextField(blank=True, max_length=500, null=True, verbose_name='리뷰')),
                ('review_point', models.IntegerField(blank=True, null=True, verbose_name='별점')),
                ('write_id', models.TextField(blank=True, max_length=50, null=True, verbose_name='작성자')),
                ('jobadvertise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userComment_jobad', to='company_profile.JobAdvertise', verbose_name='채용공고')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userComment_user', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name_plural': '리뷰 / Review',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_title', models.CharField(blank=True, default='이력서 제목', max_length=50, null=True, verbose_name='이력서 제목')),
                ('resume_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='이력서 사용자이름')),
                ('resume_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='이력서 연락처')),
                ('resume_birth', models.CharField(blank=True, max_length=8, null=True, verbose_name='이력서 생년월일')),
                ('introduce', models.TextField(blank=True, max_length=500, null=True, verbose_name='이력서 자기소개')),
                ('entry_date', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='이력서 등록일')),
                ('modify_date', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='이력서 최종수정일')),
                ('open_yn', models.BooleanField(default=False, verbose_name='이력서 공개여부')),
                ('urlkey', models.CharField(blank=True, max_length=9, null=True)),
                ('resume_file', models.FileField(null=True, upload_to=user_profile.models.resume_directory_path)),
                ('resume_filename', models.CharField(max_length=100, null=True, verbose_name='파일명')),
                ('except_company', models.ManyToManyField(blank=True, related_name='resume_except_company', to='backend.ComCode', verbose_name='이력서 제외기업')),
                ('hrprofile', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_profile.HrProfile', verbose_name='등록한회사')),
                ('resume_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ComCode', verbose_name='이력서 상태')),
                ('userspecial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='user_profile.UserSpecial')),
            ],
            options={
                'verbose_name_plural': '이력서 / Resume',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='언어 수준')),
                ('language', models.ForeignKey(blank=True, limit_choices_to={'code_topcd': None, 'comidx': 'AV'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ComCode', verbose_name='언어')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='user_profile.Resume', verbose_name='이력서')),
            ],
            options={
                'verbose_name_plural': '외국어 / Language',
            },
        ),
        migrations.CreateModel(
            name='InterestAdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobadvertise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company_profile.JobAdvertise', verbose_name='채용공고')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interestadv', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name_plural': '관심공고 / InterestAdv',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_start', models.CharField(blank=True, max_length=6, null=True, verbose_name='학력 시작')),
                ('education_end', models.CharField(blank=True, max_length=6, null=True, verbose_name='학력 종료')),
                ('school_code', models.CharField(blank=True, max_length=9, null=True, verbose_name='학교 코드')),
                ('major_detail', models.CharField(blank=True, max_length=1000, null=True, verbose_name='주요 전공')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='user_profile.Resume', verbose_name='이력서')),
            ],
            options={
                'verbose_name_plural': '학력사항 / Education',
            },
        ),
        migrations.CreateModel(
            name='CompanyAdvKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=8, verbose_name='해쉬값')),
                ('url', models.URLField(verbose_name='단축 URL')),
                ('orgUrl', models.URLField(verbose_name='Original URL')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name_plural': '기업광고URL / CompanyAdvKey',
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_start', models.CharField(blank=True, max_length=6, null=True, verbose_name='경력 시작')),
                ('career_end', models.CharField(blank=True, max_length=6, null=True, verbose_name='경력 종료')),
                ('career_company', models.CharField(blank=True, max_length=50, null=True, verbose_name='회사명')),
                ('career_dpt_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='부서명')),
                ('career_work_role', models.CharField(blank=True, max_length=1000, null=True, verbose_name='담당업무')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='user_profile.Resume', verbose_name='이력서')),
            ],
            options={
                'verbose_name_plural': '경력사항 / Career',
            },
        ),
        migrations.CreateModel(
            name='UserAdvKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=8, verbose_name='해쉬값')),
                ('url', models.URLField(verbose_name='단축 URL')),
                ('orgUrl', models.URLField(verbose_name='Original URL')),
                ('jobadvertise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company_profile.JobAdvertise', verbose_name='채용공고')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name_plural': '광고URL / UserAdvKey',
                'unique_together': {('jobadvertise', 'user')},
            },
        ),
    ]
