# Generated by Django 3.0.4 on 2021-03-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20210205_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'verbose_name_plural': '3_1. 경력사항 / Career'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name_plural': '3_2. 학력사항 / Education'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name_plural': '3 .이력서 / Resume'},
        ),
        migrations.AlterModelOptions(
            name='usercomment',
            options={'verbose_name_plural': '5. 리뷰 / Review'},
        ),
        migrations.AlterModelOptions(
            name='userpoint',
            options={'verbose_name_plural': '4. 사용자포인트 / UserPoint'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': '1. 사용자 프로필 / UserProfile'},
        ),
        migrations.AlterModelOptions(
            name='userspecial',
            options={'ordering': ['-created_time'], 'verbose_name_plural': '2. 전문분야 / UserSpecial'},
        ),
    ]
