# Generated by Django 3.0.4 on 2021-03-25 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0021_estimate_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0003_auto_20210319_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestSugub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.Sugub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
