# Generated by Django 3.0.4 on 2021-04-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20210423_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_birth',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='이력서 생년월일'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='이력서 연락처'),
        ),
    ]
